[build-system]
requires = ["setuptools", "cython", "numpy"]
build-backend = "setuptools.build_meta"
[tool.ruff]
exclude = [
    "__init__.py",
    "__main__.py",
]
ignore = ["E501"]
line-length = 80
select = [
    "B",
    "C",
    "E",
    "F",
    "W",
]

